    <a class="MenuElement" href="$TemplateAboutLink$">
      О журнале
    </a>
    <a class="MenuElement" href="$TemplateEditorial_StaffLink$">
      Редакторский состав
    </a>
    <a class="MenuElement" href="$NewsLink$">
      Новости
    </a>
    <a class="MenuElement" href="$TemplateFor_AuthorsLink$">
      Для авторов
    </a>
    <a class="MenuElement" href="$BooksLink$">
      Книги
    </a>
    <a class="MenuElement" href="$CollectionLink$">
      Коллекция номеров
    </a>
    <a class="MenuElement" href="$ForeignLink$">
      English version
    </a>