<h4>Licensing Authority</h4>
<p>
  State Publishing Committee of the Russian Federation,<br />
  North-western Regional Department, Saint-Petersburg,<br />
  Registration number: <strong><a href="../license.jpg">Эл. № ФС77-39410</a> at 15 April 2010</strong><br />
  ISSN: 1817-2172
</p>

<a name="fromLogo"></a>
<p class="jounal-index">
  The journal is indexed in Russian Science Citation Index and EBSCO
</p>

<p class="jounal-index">
  The journal is in <a href="http://vak.ed.gov.ru">Higher Attestation Commission of the Ministry of Education and Science of Russian Federation</a> list
</p>

<h4>Publisher</h4>
<p>
  Mathematics and Mechanics Faculty of Saint-Petersburg State University 
</p>

<h4>Address:</h4>
<p>
  Universitetsky prospekt, 28, 
  <br />
  198504, Peterhof, 
  <br />
  St. Petersburg, Russia. 
  <br/>
  Phone: +7 (812) 428-4210,
  <br/>
  Fax: +7 (812) 428-6944 
</p>

