<h4>Licensing Authority</h4>
<p>
  The Journal is registered by The Federal Service for Supervision of Communications, Information Technology and Mass Media (Roskomnadzor)<br />
  Registration number: <strong><a href="../license.jpg">Эл. № ФС77-39410</a> at 15 April 2010</strong><br />
  ISSN: 1817-2172
</p>

<a name="fromLogo"></a>
<p class="jounal-index">
  The journal is indexed in <a href="https://elibrary.ru/title_about.asp?id=7282">Russian Science Citation Index</a>, EBSCO, <a href="https://www.scopus.com/sourceid/21100902867">SCOPUS</a>
</p>

<p class="jounal-index">
  The journal is in
  <a href="http://vak.ed.gov.ru">Higher Attestation Commission of the Ministry of Education and Science of Russian Federation</a>
  list
</p>

<p class="jounal-index">
  All the articles are assigned with DOI
</p>


<p>
  <a href="https://www.scimagojr.com/journalsearch.php?q=21100902867&amp;tip=sid&amp;exact=no" title="SCImago Journal &amp; Country Rank"><img border="0" src="https://www.scimagojr.com/journal_img.php?id=21100902867" alt="SCImago Journal &amp; Country Rank"  /></a>
</p>

<h4>Founder and publisher</h4>
<p>
  Saint-Petersburg State University 
</p>

<h4>Address</h4>
<p>
  University Embankment, 7/9, 
  <br />
  199034, St. Petersburg, Russia.  
</p>

<h4>Editorial address</h4>
<p>
  Universitetsky prospekt, 28,
  <br />
  198504, Peterhof,
  <br />
  St. Petersburg, Russia.
  <br/>
  Phone: +7 (812) 428-4210,
  <br/>
  Fax: +7 (812) 428-6944
</p>

<h4>E-mail</h4>
<p>
  JournalDECP@gmail.com
</p>