<h4>Licensing Authority</h4>
<p>
  State Publishing Committee of the Russian Federation,<br />
  North-western Regional Department, Saint-Petersburg,<br />
  Registration number: P 2375 on March 7, 1997
</p>

<h4>Publisher</h4>
<p>
  Mathematics and Mechanics Faculty of Saint-Petersburg State University 
  <br/>
  <strong>Address:</strong>
  <br />
  Universitetsky prospekt, 28, 
  <br />
  198504, Peterhof, 
  <br />
  St. Petersburg, Russia. 
  <br/>
  Phone: +7 (812) 428-4210,
  <br/>
  Fax: +7 (812) 428-6944 
</p>

  <div id="spbstu" style="visibility:hidden">
    <p>Saint-Petersburg State Technical University</p>
  </div>

  <script type="text/javascript">
    var addr = window.location.host.toLowerCase();
    if (addr.indexOf('neva.ru') >= 0) {
      document.getElementById('spbstu').style.visibility = 'visible';
    }
  </script>
