<h3>Address</h3>
<h4>Editorial office address</h4>
<p>
198504<br /> 
Russia, Peterhof,<br /> 
Universitetskii pr., 28,<br /> 
Mathematics and Mechanics faculty,<br /> 
dept. of Computer Science<br />
</p>

<p>
Natalya B. Ampilova<br />
Assoc.Prof., Dept. of Comp. Sci, St.Petersburg State University,<br />
St. Petersburg, Russia<br />
e-mail: <a href="mailto:n.ampilova@spbu.ru">n.ampilova@spbu.ru</a>
</p>

<h4>Technical Support</h4>
<p>
    Ruslan Mokaev<br />
    St.Petersburg State University<br />
    e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>
<p>
    Elena Kudryashova<br />
    St.Petersburg State University<br />
    e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>
