<h3>Address</h3>
<h4>Editorial office address</h4>
<p>
198504<br /> 
Russia, Peterhof,<br /> 
Universitetskii pr., 28,<br /> 
Mathematics & Mechanics faculty,<br /> 
dept. of Computer Science<br />
</p>

<p>
Natalya B. Ampilova<br />
Assoc.Prof., Dept. of Comp. Sci, St.Petersburg State University,<br />
St. Petersburg, Russia<br />
tel: +7 921 415 7762<br />
e-mail: <a href="mailto:nataly@is1483.spb.edu">nataly@is1483.spb.edu</a>
</p>

<h4>Executive Secretary:</h4>
<p>
Eugene I. Petrenko<br />
Dept. of Comp. Sci, St.Petersburg State University<br />
St. Petersburg, Russia<br />
tel: +7 921 957 5331<br />
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a>
</p>
