<div class="board">

<div class="editor">
<span class="name">Sergei Abramovich</span>
<span class="title">Professor</span>
<span class="work">The State University of New York, USA</span>
<span class="email">abramovs@potsdam.edu</span>
</div>

<div class="editor">
<span class="name">Nikolay A. Bodunov</span>
<span class="title">Professor</span>
<span class="work">St. Petersburg Electrotechnical University, Russia</span>
<span class="email">nick.bodunov@gmail.com</span>
</div>


<div class="editor">
    <span class="name">Igor M. Burkin</span>
    <span class="title">Professor</span>
    <span class="work">University in Tula, Russia</span>
    <span class="email">i-burkin@yandex.ru</span>
</div>

<div class="editor">
    <span class="name">Ivan Zelinka</span>
    <span class="title">Professor</span>
    <span class="work">Technical University of Ostrava, Check Republic</span>
    <span class="email">ivan.zelinka@vsb.cz</span>
</div>

<div class="editor">
    <span class="name">Elena V. Kudryashova</span>
    <span class="title">Leading researcher</span>
    <span class="work">St. Petersburg State University, Russia</span>
    <span class="email">e.kudryashova@spbu.ru</span>
</div>

<div class="editor">
    <span class="name">Ruslan N. Mokaev</span>
    <span class="title">Senior researcher</span>
    <span class="work">St. Petersburg State University, Russia</span>
    <span class="email">r.mokaev@spbu.ru</span>
</div>

<div class="editor">
    <span class="name">Pekka Neittaanmäki</span>
    <span class="title">Professor</span>
    <span class="work">University of Jyvaskyla, Finland</span>
    <span class="email">pekka.neittaanmaki@jyu.fi</span>
</div>
    
<div class="editor">
    <span class="name">Natalia V. Stankevich</span>
    <span class="title">Senior researcher</span>
    <span class="work">HSE Nizhny Novgorod, Russia</span>
    <span class="email">stankevichnv@mail.ru</span>
</div>

<div class="editor">
    <span class="name">Igor Soloviev</span>
    <span class="title">Assoc. Prof.</span>
    <span class="work">St. Petersburg State University, Russia</span>
    <span class="email">i.soloviev@spbu.ru</span>
</div>    

<div class="editor">
    <span class="name">George S. Osipenko</span>
    <span class="title">Professor</span>
    <span class="work">Lomonosov Moscow State University, Sevastopol branch, Russia</span>
    <span class="email">george.osipenko@mail.ru</span>
</div>
    
    
<div class="editor">
    <span class="name">Sergey Y. Pilyugin</span>
    <span class="title">Professor</span>
    <span class="work">St. Petersburg State University, Russia</span>
    <span class="email">sergeipil47@mail.ru</span>
</div>

<div class="editor">
    <span class="name">Vladimir Rasvan</span>
    <span class="title">Professor</span>
    <span class="work">Craiova University, Romania</span>
    <span class="email">vrasvan@automation.ucv.ro</span>
</div>



<div class="editor">
    <span class="name">Volker Reitmann</span>
    <span class="title">Professor</span>
    <span class="work">St. Petersburg State University, Russia</span>
    <span class="email">vreitmann@aol.com</span>
</div>

<div class="editor">
    <span class="name">Alexander V. Flegontov</span>
    <span class="title">Professor</span>
    <span class="work">St.Petersburg Herzen State Pedagogical University of Russia</span>
    <span class="email">flegontoff@yandex.ru</span>
</div>

<div class="editor">
    <span class="name">Guanrong Chen</span>
    <span class="title">Professor</span>
    <span class="work">City University of Hong Kong (China)</span>
    <span class="email">eegchen@cityu.edu.hk</span>
</div>

<div class="editor">
    <span class="name">Leonid Chechurin</span>
    <span class="title">Professor</span>
    <span class="work">Lappeenranta University of Technology (LUT), Finland</span>
    <span class="email">Leonid.Chechurin@lut.fi</span>
</div>

<div class="editor">
    <span class="name">Magomet M. Shumafov</span>
    <span class="title">Professor</span>
    <span class="work">Adyghe State University, Russia</span>
    <span class="email">magomet_sh@mail.ru</span>
</div>
</div>