<h2>$editodial_page_caption()$</h2>

$about_content()$

<h3>Editor-in-Chief</h3>
<ul>
  <li>Gennadii Alexeevich Leonov, corresponding member of RAS, professor, Doctor of Science</li>
</ul>

<h3>Editor</h3>
<ul>
  <li>Natalia Borisovna Ampilova, Assoc.prof., PhD</li>
</ul>

<h3>Technical Support</h3>
<ul>
  <li>Eugene Igorevich Petrenko, PhD</li>
</ul>

$editorial_editorial_board()$