<h3>Publishing Board</h3>
<ul>
<li>A.G. Chentzov (Dr. Sci., Ekaterinburg),</li>
<li>A.V. Flegontov (Dr. Sci., St. Petersburg), </li>
<li>A.L. Fradkov (Dr. Sci., St. Petersburg),</li>
<li>C.K. Korovin (Dr. Sci., Moscow),</li>
<li>N.N. Krasovskii (Dr. Sci., Ekaterinburg),</li>
<li>A.B. Kurshanskii (Dr. Sci., Moscow),</li>
<li>G.A. Leonov (Dr. Sci., St. Petersburg),</li>
<li>L.A. Mironovskii (Dr. Sci., St. Petersburg),</li>
<li>G.S. Osipenko (Dr. Sci.), </li>
<li>V.A. Palmov (Dr. Sci., St. Petersburg),</li>
<li>L.A. Petrosian (Dr. Sci., St. Petersburg),</li>
<li>V.A. Pliss (Dr. Sci., St. Petersburg),</li>
<li>N.C. Rosov (Dr. Sci., Moscow),</li>
<li>V.A. Yakubovitch (Dr. Sci., St. Petersburg)</li>
</ul>
