<h3>Editorial Board</h3>

<div class="board">

<div class="editor">
<span class="name">Sergei Abramovich  </span>
<span class="work">The State University of New York (USA)</span>
<span class="email">abramovs@potsdam.edu</span>
</div>
<div class="editor">
<span class="name">Alexey F. Andreev  </span>
<span class="work">St.Peterburg State University (Russia)</span>
<span class="email">irandr124@gmail.com</span>
</div>
<div class="editor">
<span class="name">Jan Awrejcewicz  </span>
<span class="work">The Lodz University of Technology (Poland)</span>
<span class="email">jan.awrejcewicz@p.lodz.pl</span>
</div>
<div class="editor">
<span class="name">Nikolay A. Bodunov</span>
<span class="work">St. Petersburg Electrotechnical University (Russia)</span>
<span class="email">nick.bodunov@gmail.com</span>
</div>
<div class="editor">
<span class="name">Guanrong Chen</span>
<span class="work">City University of Hong Kong (China)</span>
<span class="email">eegchen@cityu.edu.hk</span>
</div>
<div class="editor">
<span class="name">Alexander L. Fradkov</span>
<span class="work">Institute for Problems of Mechanical Engineering RAS (Russia)</span>
<span class="email">fradkov@mail.ru</span>
</div>
<div class="editor">
<span class="name">Nikolay V. Kuznetsov </span>
<span class="work">University of Jyvaskyla (Finland)</span>
<span class="work">St. Petersburg State University (Russia)</span>
<span class="email">kuznetsov@math.spbu.ru</span>
</div>
<div class="editor">
<span class="name">Pekka Neittaanmäki </span>
<span class="work">University of Jyvaskyla (Finland)</span>
<span class="email">pekka.neittaanmaki@jyu.fi</span>
</div>
<div class="editor">
<span class="name">Alexey S. Matveev </span>
<span class="work">St. Petersburg State University (Russia)</span>
<span class="email">almat1712@yahoo.com</span>
</div>
<div class="editor">
<span class="name">George S. Osipenko</span>
<span class="work">Lomonosov Moscow State University, Sevastopol branch (Russia)</span>
<span class="email">george.osipenko@mail.ru</span>
</div>
<div class="editor">
<span class="name">Sergey Y. Pilyugin</span>
<span class="work">St. Petersburg State University (Russia)</span>
<span class="email">sergeipil47@mail.ru</span>
</div>
<div class="editor">
<span class="name">Volker Reitmann </span>
<span class="work">DAAD (Germany)</span>
<span class="email">vreitmann@aol.com</span>
</div>
<div class="editor">
<span class="name">Valentin F. Zaitsev </span>
<span class="work">St.Petersburg Herzen State Pedagogical University of Russia </span>
<span class="email">valentin_zaitsev@mail.ru </span>
</div>
<div class="editor">
<span class="name">Mikhail Zakrževskis</span>
<span class="work">Riga Technical University (Latvia)</span>
<span class="email">mzakr@latnet.lv</span>
</div>
<div class="editor">
<span class="name">Ivan Zelinka</span>
<span class="work">Technical University of Ostrava (Check Republic)</span>
<span class="email">ivan.zelinka@vsb.cz</span>
</div>

</div>