<h2>$editodial_page_caption()$</h2>

$about_content()$

<h3>Editor-in-Chief</h3>
<ul><li>George S. Osipenko</li></ul>

<h3>Assistant Editors</h3>
<ul>
  <li>Alexandr V. Flegontov</li>
  <li>Sergey Yu. Pilyugin</li>
</ul>

<h3>Editor</h3>
<ul>
  <li>Natalya B. Ampilova</li>
</ul>

<h3>Executive Secretary</h3>
<ul>
  <li>Eugene I. Petrenko</li>
</ul>


$editorial_publishing_board()$

$editorial_editorial_board()$