
<h3>Editor-in-Chief</h3>
<h4>Nikolay V. Kuznetsov</h4>
<p>
Dr. of Sci., Professor<br />
St. Petersburg State University, Russia
</p>

<h3>Editor</h3>
<h4>Natalya B. Ampilova</h4>
<p>
Assoc.Prof., Dept. of Comp. Sci<br />
St. Petersburg State University, Russia<br />
tel: +7 921 415 7762 <br />
e-mail: <a href="mailto:n.ampilova@spbu.ru">n.ampilova@spbu.ru</a>
</p>

<h3>Technical Support</h3>
<h4>Eugene I. Petrenko</h4>
<p>PhD<br />
St. Petersburg State University, Russia<br />
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a>
</p>

$editorial_editorial_board()$
