
<h3>Editor-in-Chief</h3>
<h4><a href="http://apcyb.spbu.ru/nk">Nikolay Kuznetsov</a></h4>
<p>
Dr. of Sci., Professor<br />
St. Petersburg State University, Russia <br />
e-mail: <a href="mailto:n.v.kuznetsov@spbu.ru">n.v.kuznetsov@spbu.ru</a>
</p>

<h3>Deputy Editor</h3>
<h4>Natalya Ampilova</h4>
<p>
Assoc.Prof., Dept. of Comp. Sci<br />
St. Petersburg State University, Russia<br />
tel: +7 921 415 7762 <br />
e-mail: <a href="mailto:n.ampilova@spbu.ru">n.ampilova@spbu.ru</a>
</p>

<h3>Technical Support</h3>
<h4>Eugene <!-- @jonnyzzz --> Petrenko</h4>
<p>PhD<br />
St. Petersburg State University, Russia<br />
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a>
</p>

<h4>Ruslan Mokaev</h4>
<p>Cand. of Sci.<br />
St. Petersburg State University, Russia<br />
e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>

<h4>Elena Kudryashova</h4>
<p>PhD<br />
    St. Petersburg State University, Russia<br />
    e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>

$editorial_editorial_board()$
