<h2>$editodial_page_caption()$</h2>

$about_content()$

<h3>Editor-in-Chief</h3>
<ul>
  <li><strong>Nikolay Kuznetsov</strong><br />professor, Doctor of Science</li>
</ul>

<h3>Deputy Editor</h3>
<ul>
  <li><strong>Natalia Ampilova</strong><br />Assoc.prof., PhD</li>
</ul>

<h3>Technical Support</h3>
<ul>
  <li><strong>Eugene <!-- @jonnyzzz --> Petrenko</strong><br />PhD</li>
</ul>

$editorial_editorial_board()$