<h3>Editorial Board:</h3>
<ul>
<li>A.F. Andreev (Dr. Sci., St. Petersburg),</li>
<li>N.E. Barabanov (Dr. Sci., St. Petersburg),</li>
<li>Yu.N. Bibikov (Dr. Sci., St. Petersburg),</li>
<li>Yu.V. Churin (Dr. Sci., St. Petersburg),</li>
<li>V.M. Ivanov (Dr. Sci., St. Petersburg),</li>
<li>E.K. Ershov (Assoc.Prof., St. Petersburg),</li>
<li>V.N. Kozlov (Dr. Sci., St. Petersburg),</li>
<li>N.V. Kuznetsov (Assoc. Prof., St. Petersburg),</li>
<li>G.G. Malinechkii (Dr. Sci., Moscow),</li>
<li>A.S. Matveev (Dr. Sci., St. Petersburg),</li>
<li>I.V. Miroshnik (Dr. Sci., St. Petersburg),</li>
<li>N.N. Petrov (Dr. Sci., St. Petersburg),</li>
<li>S.Yu. Piliugin (Dr. Sci., St. Petersburg),</li>
<li>G.Yu. Riznichenko (Dr. Sci., Moscow),</li>
<li>E.N. Rozenvasser (Dr. Sci., St. Petersburg),</li>
<li>A.I. Shepeliavui (Assoc.Prof., St. Petersburg),</li>
<li>V.B. Smirnova (Dr. Sci., St. Petersburg),</li>
<li>A.V. Timofeev (Dr. Sci., St. Petersburg),</li>
<li>S.M. Ustinov (Dr. Sci., St. Petersburg),</li>
<li>V.F. Zaitsev (Dr. Sci., St. Petersburg),</li>
<li>A.V. Zinkovskii (Dr. Sci., St. Petersburg)</li>
</ul>