
<h3>Editor-in-Chief - <a href="https://en.wikipedia.org/wiki/Nikolay_V._Kuznetsov">Nikolay Kuznetsov</a></h3>
<!--<h4><a href="https://en.wikipedia.org/wiki/Nikolay_V._Kuznetsov">Nikolay Kuznetsov</a></h4>-->
<p>Corresponding member of RAS, Dr. of Sci., Professor<br />
St. Petersburg State University, Russia <br />
e-mail: <a href="mailto:n.v.kuznetsov@spbu.ru">n.v.kuznetsov@spbu.ru</a>
</p>

<h3>Deputy Editor - Natalya Ampilova</h3>
<!--<h4>Natalya Ampilova</h4>-->
<p>
Assoc. Prof., Dept. of Comp. Sci<br />
St. Petersburg State University, Russia<br />
tel: +7 921 415 7762 <br />
e-mail: <a href="mailto:n.ampilova@spbu.ru">n.ampilova@spbu.ru</a>
</p>

<h3>Editor - Soloviev Igor</h3>
<p>Assoc. Prof.<br />
    St. Petersburg State University, Russia<br />
    e-mail: <a href="mailto:i.soloviev@spbu.ru">i.soloviev@spbu.ru</a>
</p>

$editorial_editorial_board()$
