<div style="text-align:justify; width:80%">

<h2>Publication Ethics and Malpractice Statement</h2>
<p>
The editorial board of the electronic journal “Differencial’nye uravnenia I processy upravlenia (Differential equation and control processes)” follows ethics norms accepted by international scientific community and makes every endeavor to prevent any infringements of the norms. The board follows the guidelines of Committee  of  Publication Ethics.
</p>

<h3>Duties of Editors</h3>
<ul>
<li>All submitted papers are subject to strict peer-review process by international reviewers that are experts in the area of the particular paper.
</li><li>The factors that are taken into account in review are relevance, soundness, significance, originality, readability and language.
</li><li>The possible decisions include acceptance, acceptance with revisions, or rejection.
</li><li>If authors are encouraged to revise and resubmit a submission, there is no guarantee that the revised submission will be accepted.
</li><li>Rejected articles will not be re-reviewed.
</li><li>Articles may be rejected without review if they are obviously not suitable for publication.
</li><li>The paper acceptance is constrained by such legal requirements as shall then be in force regarding libel, copyright infringement and plagiarism.
</li>
</ul>
<p>
When a conflict of interests arising, all the participants of reviewing process should inform the editorial board. All the contentions questions are considered in the board meeting.
</p>

<p>The accepted papers are allocated in open access on the journal site; copyrights reserved.</p>

<h3>Duties of Reviewers</h3>
<ul>
<li>The reviewers evaluate manuscripts for their intellectual content without regard to race, gender, sexual orientation, religious belief, ethnic origin, citizenship, or political philosophy of the authors.
</li><li>The staff must not disclose any information about a submitted manuscript to anyone other than the corresponding author, reviewers, other editorial advisers, and the publisher, as appropriate.
</li><li>Reviews should be conducted objectively. Personal criticism of the author is inappropriate. Referees should express their views clearly with supporting arguments.
</li><li>Peer review assists the publisher in making editorial decisions and through the editorial communications with the experts form the scientific board ant the author may also assist the author in improving the paper.
</li><li>Manuscripts received for review are treated as confidential documents and are reviewed by anonymous staff.
</li><li>A reviewer should also call to the publisher's attention any substantial similarity or overlap between the manuscript under consideration and any other published paper of which they have personal knowledge.
</li></ul>

<h3>Duties of Authors</h3>
<ul>
<li>Authors of contributions and studies research should present an accurate account of the work performed as well as an objective discussion of its significance.
</li><li>A paper should contain sufficient detail and references to permit others to replicate the work. Fraudulent or knowingly inaccurate statements constitute unethical behavior and are unacceptable.
</li><li>The authors should ensure that they have written entirely original works, and if the authors have used the work and/or words of others that this has been appropriately cited or quoted.
</li><li>Submitting the same manuscript to more than one publication concurrently constitutes unethical publishing behaviour and is unacceptable.
</li><li>Authorship should be limited to those who have made a significant contribution to the conception, design, execution, or interpretation of the reported study.
</li><li>All sources of financial support for the project should be disclosed.
</li></ul>
 

</div>