<h2>Preparation of a paper in English</h2>

<p>If the paper is in Russian, see <a href="$ForeignLink$">Preparation of a paper in Russian</a> </p>

<p>A paper submission MUST include:
<ul>
  <li>Files of the paper in <a href="http://www.miktex.org">MikTex 2.9 (LaTeX)</a> 
		or <a href="http://www.microsoft.com/office">Microsoft Word</a> formats</li>
  <ul>
    <li><strong>Journal <a href="#template-files">templates</a> must be used</strong></li>
    <li>It is necessary to add the affiliation after the title</li>
  </ul>
  <li>PDF-file of the paper</li>
  <li>Text file in Plain Text or HTML containing:</li>
  <ul>
      <li>paper title</li>
      <li>surname, first name, patronymic</li>
      <li>affiliation (work place, institution, address, position)</li>
      <li>academic status and degree</li>      
      <li>abstract</li>      
      <li>e-mail (to be published in open access)</li>
      <li>phone, fax</li>
  </ul>
  <li>The file containing references in HTML or Markdown format</li>
  <ul>
     <li>For russian paper references, see <a href="$TemplateFor_Authors_RefsLink$">Russian References</a></li>
  </ul>
</ul>
</p>

<p>
  The paper is prepared in accordance with the journal style following the instruction for authors.
  The paper size is not limited.
</p>

<p>Please send your prepared paper to both e-mail addresses:
   <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a> 
   and 
   <a href="mailto:n.ampilova@spbu.ru">n.ampilova@spbu.ru</a>.
</p>


<h2>Electronic publication</h2>
<ul>
  <li>The paper abstract, pdf-file and references are published at the Journal home page in the Internet</li>
  <li>Author is responsible for solving any issues with preparation of the materials</li>
</ul> 

<h2>Preparation of the article in TEX-format</h2>
<a name="template-files"> </a>
<p>You should use <a href="http://www.miktex.org">MikTex 2.9+</a> with journal templates</p>
<p>How to apply the templates for MikTex:
 <ul>
   <li>Download file <a href="$ResourceLink$/auth-for-tex.zip">author-for-tex.zip</a> from the journal site to your computer and unpack it</li>
   <li>Select the folder <em>eng</em> </li>
   <li>Open file <em>english.tex</em> and follow instructions from comments in the file (write your paper title, authors, and the first page number)</li>
   <li>Open file <em>diff_eng.sty</em> and write the journal number and the year of publishing</li>
   <li>Open file <em>diff_eng.tex</em> and write the journal number, the year of publishing and the field of study that the paper relates</li>
   <li>Check that your article is compiled by the command "<em>pdflatex english.tex</em>" in MikTex 2.9+</li>
 </ul>
</p>
<p>Information about last versions of TEX you can find on the site <a href="http://www.miktex.org">http://www.miktex.org</a>.
LaTeX is a module in the MikTEX package</p>

<h2>Preparation of the article in Microsoft Word</h2>
<p>
 <ul>
    <li>Download file <a href="$ResourceLink$/auth-for-doc.zip">author-for-doc.zip</a> from the journal site and unpack it</li>
    <li>Select folder <em>eng</em></li>
    <li>Open <em>Dif_eng.dot</em> in the Microsoft Word</li>
    <li>In obtained file fill in the fields: <b>[number], [year], [Theme], [Title], [AUTHOR NAME], [address]</b></li>
    <li>Copy the text of your article in to the file. At the top and the bottom of each page (but cover page) running titles appear</li>
    <li>On the second page double click by mouse left button on the string "Differential Equations and Control Processes, [ number], [year]") and fill in the fields</li>
    <li>Save the document as <em>YOUR_NAME-art.doc</em></li>
 </ul>
</p>