<h2>Preparation of a paper</h2>
<p>A paper submission MUST include:
<ul>
  <li>Files of the paper in <a href="http://www.miktex.org">MikTex 2.7(LaTeX)</a> 
		or <a href="http://www.microsoft.com/office">Microsoft Word</a> formats.
		<strong>Journal <a href="#template-files">templates</a> must be used</strong>
		</li>
  <li>PDF-file of the paper</li>
  <li>Text file (in english):
    <ul>
	  <li>paper title</li>
      <li>abstracts</li>      
      <li>surname, first name, patronymic</li>
      <li>postal address</li>
      <li>e-mail (to be published in open access)</li>
      <li>phone, fax</li>
      <li>institution and position</li>
      <li>academic status and degree</li>      
    </ul>
  </li>
  <li>If the paper is in Russian, the same text file in russian is required</li>
  <li>Covering letter containing:
    <ul>
      <li>a fields of study which the paper relates to</li>
      <li>possible referees of the paper</li>
    </ul>
  </li>
</ul>
</p>

<p>
  The paper is to be prepared in accordance with the journal's style following the instruction for authors.
  The paper size is not limited.
</p>

<p>Note. The submitted materials are not taken back.</p>

<p>Papers are to be sent to e-mail:
   <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a> 
   and 
   <a href="mailto:nataly@is1483.spb.edu">nataly@is1483.spb.edu</a>.
</p>


<h2>Electronic publication contains of:</h2>
<ul>
  <li>Paper's abstract and pdf-file published at the Journal home page in the Internet.</li>
  <li>The notification is sent to the author.</li>
  <li>Author is responsible for solving any issues with preparation of the materials.</li>
</ul> 

<h2>Preparation of the article in  TEX-format</h2>
<a name="template-files"> </a>
<p>When preparing an article you should use <a href="http://www.miktex.org">MikTex 2.7</a> and templates.</p>
<p>How to apply the templates for MikTex:
 <ul>
   <li>Download file <a href="$ResourceLink$/auth-for-tex.zip">author-for-tex.zip</a> from the journal site to your computer and unpack it. </li>
   <li>Select  folder eng or rus according to the paper language.</li>
   <li>Open file Russian.tex, name your paper file, and page number, following the comments in tex-file.</li>
   <li>Open file diff_eng.sty or diff_rus.sty and name the journal number and the year of publishing.</li>
   <li>Open file diff_eng.tex or diff_rus.tex and name the journal number, the year of publishing and the field of study that the paper relates.</li>
   <li>Check that your article is compiled  by the command "pdflatex Russian.tex"  in MikTex 2.7+.</li>
 </ul>
</p>
<p>Information about last versions of Tex you can find on the site <a href="http://www.miktex.org">http://www.miktex.org</a>. 
LaTeX is a module in the MikTex package. </p>

<h2>Preparation of the article in Microsoft Word</h2>
<p>
 <ul>
    <li>Download file <a href="$ResourceLink$/auth-for-doc.zip">author-for-doc.zip</a> from the journal site and unpack it.
    <li>Select folder eng or rus according to the paper language. 
    <li>Make a double click by mouse left button on  Dif_eng.dot ( Dif_rus.dot) .
    <li>In obtained file fill  in the fields: <b>[number], [year], [Theme], [Title], [AUTHOR NAME], [address]</b></li>
    <li>Copy the text of your article in this file. At the top and the bottom of each page (but cover page) running titles appear.</li>
    <li>On the second page double click by mouse left button on the string "Differential Equations and Control Processes,   [ number], [year]")  and fill in the fields.</li>
    <li>Save the document as name-art.doc, where 'name' is author name.</li>
 </ul>
</p>