<h2>Preparation of a paper</h2>
<p>A paper submission MUST include:
<ul>
  <li>Files of the paper in <a href="http://www.miktex.org">MikTex 2.9 (LaTeX)</a> 
		or <a href="http://www.microsoft.com/office">Microsoft Word</a> formats</li>
  <ul>
    <li><strong>Journal <a href="#template-files">templates</a> must be used</strong></li>
    <li>It is necessary to add the affiliation after the title</li>
  </ul>
  <li>PDF-file of the paper</li>
  <li>Text file in Plain Text or HTML (in english):</li>
  <ul>
      <li>paper title</li>
      <li>surname, first name, patronymic</li>
      <li>affiliation (work place, institution, address, position)</li>
      <li>academic status and degree</li>      
      <li>abstracts</li>      
      <li>e-mail (to be published in open access)</li>
      <li>phone, fax</li>
  </ul>
  <li>the file containing references in HTML or Markdown format</li>
  <ul><li>For russian paper references, see <a href="$TemplateFor_Authors_RefsLink$">Russian References</a></li></ul>
  <li>If the paper is in Russian, the same texts file in russian are required</li>
</ul>
</p>

<p>
  The paper is prepared in accordance with the journal style following the instruction for authors.
  The paper size is not limited.
</p>

<p>Please send your prepared paper to both e-mail addresses:
   <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a> 
   and 
   <a href="mailto:n.ampilova@spbu.ru">n.ampilova@spbu.ru</a>.
</p>


<h2>Electronic publication</h2>
<ul>
  <li>The paper abstract, pdf-file and references are published at the Journal home page in the Internet</li>
  <li>The notification is sent to the author</li>
  <li>Author is responsible for solving any issues with preparation of the materials</li>
</ul> 

<h2>Preparation of the article in TEX-format</h2>
<a name="template-files"> </a>
<p>You should use <a href="http://www.miktex.org">MikTex 2.9+</a> with journal templates</p>
<p>How to apply the templates for MikTex:
 <ul>
   <li>Download file <a href="$ResourceLink$/auth-for-tex.zip">author-for-tex.zip</a> from the journal site to your computer and unpack it</li>
   <li>Select  folder eng or rus according to the paper language</li>
   <li>Open file Russian.tex, name your paper file, and page number, following the comments in tex-file</li>
   <li>Open file diff_eng.sty or diff_rus.sty and name the journal number and the year of publishing</li>
   <li>Open file diff_eng.tex or diff_rus.tex and name the journal number, the year of publishing and the field of study that the paper relates</li>
   <li>Check that your article is compiled  by the command "pdflatex Russian.tex" in MikTex 2.9+</li>
 </ul>
</p>
<p>Information about last versions of Tex you can find on the site <a href="http://www.miktex.org">http://www.miktex.org</a>.
LaTeX is a module in the MikTex package. </p>

<h2>Preparation of the article in Microsoft Word</h2>
<p>
 <ul>
    <li>Download file <a href="$ResourceLink$/auth-for-doc.zip">author-for-doc.zip</a> from the journal site and unpack it</li>
    <li>Select folder eng or rus according to the paper language</li>
    <li>Make a double click by mouse left button on  Dif_eng.dot (Dif_rus.dot)</li>
    <li>In obtained file fill  in the fields: <b>[number], [year], [Theme], [Title], [AUTHOR NAME], [address]</b></li>
    <li>Copy the text of your article in this file. At the top and the bottom of each page (but cover page) running titles appear</li>
    <li>On the second page double click by mouse left button on the string "Differential Equations and Control Processes, [ number], [year]")  and fill in the fields</li>
    <li>Save the document as name-art.doc, where 'name' is the author name</li>
 </ul>
</p>