<html>
  <head>
    <title>$title$</title>
    <link rel="stylesheet" href="$style$" type="text/css">
  </head>
  <body>
    <div class="head">
      <div class="logo">This is a logo</div>
      <h1>Journal head</h1>
    </div>
    

    <div class="content">
        $content$
        <a class="lang" href="$ForeignLink$"> Translated link here $ForeignLink.Language$ </a>
    </div>

  </body>
</html>