<div class="policy-page">

    <h2>Personal Data Policy</h2>

    <p>
        The names, email addresses and other personal data entered on this journal
        website will be used exclusively for the purposes of the journal and will not
        be made available for any other purpose or to any other party, except as
        provided for by the applicable legislation of the Russian Federation.
    </p>

    <p>
        <a class="external-policy-link"
           href="https://english.spbu.ru/about/documents/policy-federal-state-budgetary-educational-institution-higher-education-st">
            Policy of the Federal State Budgetary Educational Institution of Higher
            Education 'St. Petersburg State University' regarding the Processing of
            Personal Data
        </a>
    </p>


    <h2>Consent to the Processing of Personal Data</h2>

    <p>
        By this action, I, hereinafter referred to as the 'Data Subject', in compliance
        with the requirements of Federal Law No. 152-FZ of 27 July 2006 'On Personal
        Data', hereby give my consent to the Personal Data Operator (SPbU) to process
        my personal data provided by completing the web form on the SPbU website at
        https://diffjournal.spbu.ru (hereinafter referred to as the 'Website'),
        submitted (completed) using the Website, including information provided by
        completing a web form on the Website.
    </p>

    <p>
        By 'processing of personal data', I understand the collection, recording,
        systematisation, accumulation, storage, updating, modification, use, transfer,
        anonymisation, blocking, deletion, destruction, indefinite retention, and any
        other actions (operations) with personal data performed by the Personal Data
        Operator as provided for by the applicable legislation of the Russian
        Federation.
    </p>

    <p>
        The processing of the Data Subject's personal data is carried out for the
        purposes of sending information messages regarding SPbU, providing advisory
        support by authorised SPbU staff, responding to enquiries submitted via the
        web form on the Website, and for other purposes provided for by the applicable
        legislation of the Russian Federation.
    </p>

    <p>
        The processing of the Data Subject's personal data may be carried out using
        automation tools and/or without the use of automation tools in accordance
        with the applicable legislation of the Russian Federation.
    </p>

    <p>
        SPbU takes the necessary legal, organisational and technical measures, or
        ensures that such measures are taken, to protect personal data from unlawful
        or accidental access, destruction, alteration, blocking, copying, provision,
        distribution, and from other unlawful actions in relation to personal data,
        and also undertakes to maintain the confidentiality of the Data Subject's
        personal data.
    </p>

    <p>
        This consent to the processing of my personal data provided by completing
        the web form on the Website, submitted (completed) using the Website, is
        effective from the moment the web form is submitted on the Website until
        the purposes of the processing are achieved or until the consent is withdrawn.
    </p>

    <p>
        The consent may be withdrawn by me on the basis of a written application sent
        to the Personal Data Operator.
    </p>


    <h2>Consent to the Processing of Personal Data Collected via Metric Programmes</h2>

    <p>
        By continuing to use the website https://diffjournal.spbu.ru (hereinafter referred to as the
        ''Website'') and clicking the ''Accept'' or ''Agree'' button on the Website, I, hereinafter referred
        to as the ''Data Subject'', pursuant to Federal Law No. 152 FZ of 27 July 2006 ''On Personal
        Data'', hereby consent to the processing of my personal data by the Personal Data Operator,
        the Federal State Budgetary Educational Institution of Higher Education ''St. Petersburg
        State University'' (hereinafter referred to as ''SPbU''), registered at 7-9 Universitetskaya
        Embankment, St. Petersburg, Russia, 199034. The personal data to be processed include:
        Website traffic data; data on user behaviour, including pages viewed, page-view depth, the
        date, time and duration of visits, and geolocation data; the type of device used, its operating
        and browser type; the source from which the Website was accessed; information about
        search queries or advertising queries; forms completed by the user; and actions performed
        by the user aimed at achieving specific results when interacting with the Website, including,
        but not limited to, submitting applications, registering a personal account, subscribing to
        email newsletters, downloading materials, and paying for goods or services. I also consent
        to the collection of the aforesaid data using the ''webstat.spbu.ru'' and ''Yandex.Metrica''
        services.
    </p>

    <p>
        The data collected via the ''Yandex.Metrica'' web analytics system may be transferred to
        the owner of such system: Yandex LLC, INN (Taxpayer Identification Number) 7736207543,
        OGRN (Primary National Registration Number) 1027700229193, registered address: 16 Lva
        Tolstogo Street, Moscow, Russia, 119021. The abovementioned personal data will not be
        transferred to other countries.
    </p>

    <p>    For the purposes of this Consent, the processing of personal data means the
        collection, recording, systematisation, accumulation, clarification, updating, modification,
        use, transfer, disclosure, anonymisation, blocking, deletion, destruction and storage of
        personal data by the Personal Data Operator as provided for by the applicable legislation of
        the Russian Federation.
    </p>

    <p>    The personal data of the Data Subject are processed for the following purposes:
        analysing user behaviour; aggregating statistical data on Website traffic over selected
        periods; analysing Website traffic trends; evaluating the effectiveness of traffic sources;
        assessing user conversions (metrics for completed target actions); improving the usability
        and quality of the Website; and obtaining statistical information. When personal data are
        collected, their recording, systematisation, accumulation, storage, clarification (updating
        and modification) and retrieval of personal data are carried out using databases located
        within the territory of the Russian Federation.
    </p>

    <p>    The processing of the Data Subject’s personal data may be carried out with and/or
        without the use of automated means, in accordance with the applicable laws of the Russian
        Federation.
    </p>

    <p>    The St. Petersburg Sate University Policy regarding the Processing of Personal Data
        is available at the following link.
    </p>

    <p>   St. Petersburg State University shall take the necessary legal, organisational and
        technical measures, or ensure that such measures are taken, to protect personal data against
        unlawful or accidental access, destruction, alteration, blocking, copying, disclosure or

        dissemination, as well as against other unlawful actions with respect to personal data. SPbU
        shall also undertake to maintain the confidentiality of the Data Subject’s personal data.
    </p>

    <p>    This Consent to the processing of my personal data shall remain valid from the start
        of data collection using the ''webstat.spbu.ru'' and ''Yandex.Metrica'' services until the purpose
        of the processing of personal data has been achieved or this Consent is withdrawn.
    </p>

    <p>    This Consent may be withdrawn upon my written request submitted to the Personal
        Data Operator.
    </p>

</div>