<h2>$review_caption()$</h2>

<ol>
     <li>All submitted papers are subject to strict peer-review process by international reviewers that are experts in the area of the particular paper. 
</li><li>The editor-in-chief verifies the correspondence of the paper to the journal scope. On the basis of the editorial board recommendation the editor sends the paper to a reviewer, who is expert in the area close to the paper subject and has publications in this area during last 3 years.
</li><li>Manuscripts received for review are treated as confidential documents and are reviewed by anonymous staff. The reviewers are informed that the sent documents are author's private property and must not be disclosed.
</li><li>The reviewing is confidential. The confidentiality may be broken only if the reviewer claims about an inauthenticity or falsification of the matters given in the paper.
</li><li>Periods of reviewing are stated by the editor-in-chief to provide the paper publishing as much as possible.
</li><li>The review is sent to the author by e-mail. Copies of review are saved in editorial office.
</li><li>If in the review there are remarks and the paper revision proposals, the author should correct the paper and resend it. In this case the day of the paper entry is the day of entry of the revised version.
</li><li>Papers not recommended for the publication are not considered for the repeated review. 
</li><li>The reviewed paper publishing decision is made by the editor-in-chief as agreed with editorial board.
</li><li>The editorial board sends copies of reviews to the Ministry of Higher Education of Russian Federation providing that the inquiry was made.
</li>


</ol>
