<h2>Scope of the Journal</h2>
<p>Lectures and courses of lectures, theses and author's abstracts, computer software, and other items with a detailed exposition of results, proofs, and examples.</p>

<p>According to the journal scope, the Editorial Board accepts educational courses and software, methodological papers, materials on teaching methods, and information about monographs, textbooks, theses, software, seminars, and conferences.</p>

<h3>The scope of the journal encompasses the following fields of study:</h3>
 <ul>
   <li>ordinary differential equations </li>
   <li>nonlinear oscillations </li>
   <li>differential-difference equations </li>
   <li>dynamical systems on manifolds </li>
   <li>bifurcation </li>
   <li>symbolic dynamics </li>
   <li>integro-differential equations </li>
   <li>group analysis of differential equations </li>
   <li>differential equations with randomness </li>
   <li>general control problems </li>
   <li>adaptive and robust control </li>
   <li>control problems in nonlinear and sophisticated systems </li>
   <li>filtration and identification </li>
   <li>synchronization of oscillatory and chaotic processes </li>
   <li>optimal control </li>
   <li>numerical methods </li>
   <li>computer modeling in dynamical and control systems </li>
   <li>computer software for investigation of differential </li>
   <li>equations, dynamical systems, and control processes </li>
   <li>applications to physics, electrotechnics, and electronics </li>
   <li>dynamical systems in medicine, biology, ecology, and chemistry </li>
   <li>control in social and economical systems</li>
   <li>information systems and processes</li>
   <li>AI and machine learning in control processes</li>
 </ul>

<h3>The working languages of the Journal are English and Russian.</h3>
