<h4>Журнал зарегистрирован</h4>
<p>
  Комитетом по печати Российской Федерации.<br> 
  Северо западное региональное управление. Санкт-Петербург.<br>
  Регистрационный номер: П 2375 от 07 марта 1997г.<br>
</p>

<p>
  <div id="issn2">ISSN 1817-2172</div>
  <script type="text/javascript">
    var addr = window.location.host.toLowerCase();
    if (addr.indexOf('neva.ru') > 0) {
      document.getElementById('issn2').style.visibility = 'hidden';
    }
  </script>
</p>



<h4>Учредитель</h4>
<p>
  Математико-механический факультет Санкт-Петербургского Государственного университета
</p>

<h4>Адрес:</h4>
<p>
  198504, Россия, Санкт-Петербург, 
  <br/>
  Старый Петергоф, 
  <br />
  Университетский пр., дом 28.   
  <br />
  тел: (812) 428-4210,
  <br />
  факс: (812) 428-6944
</p>

<div id="spbstu" style="visibility:hidden;display:none;">
  <h4>Учредитель</h4>
  <p>Санкт-Петербургский Государственный Технический Университет</p>
</div>
   
<script type="text/javascript">
    var addr = window.location.host.toLowerCase();
    if (addr.indexOf('.neva.ru') >= 0) {
       document.getElementById('spbstu').style.visibility = 'visible';
       document.getElementById('spbstu').style.display = 'block';
    }
</script>

