<h4>Журнал зарегистрирован:</h4>
<p>
  Комитетом по печати Российской Федерации.<br> 
  Северо западное региональное управление. Санкт-Петербург.<br>
  Регистрационный номер: П 2375 от 07 марта 1997г.<br>
</p>

<h4>Учредитель:</h4>

<p>
  Санкт-Петербургский Государственный Университет
</p>

<div id="spbstu" style="visibility:hidden">
  <p>Санкт-Петербургский Государственный Технический Университет.</p>
</div>
      
        <script type="text/javascript">
          var addr = window.location.host.toLowerCase();
          if (addr.indexOf('neva.ru') >= 0) {
            document.getElementById('spbstu').style.visibility = 'visible';
          }
        </script>

