<p>
  Журнал зарегистрирован Федеральной службой по надзору в сфере связи,
  информационных технологий и массовых коммуникаций (Роскомнадзор).<br/>
  Регистрационный номер: <strong><a href="../license.jpg">Эл. № ФС77-39410</a> от 15 апреля 2010</strong> <br/>
  ISSN: <strong>1817-2172</strong>
</p>


<a name="fromLogo"></a>
<p class="jounal-index">
  Журнал индексируется в <a href="https://elibrary.ru/title_about.asp?id=7282">РИНЦ</a>, EBSCO, <a href="https://www.scopus.com/sourceid/21100902867">SCOPUS</a>
</p>

<p class="jounal-index">
  Журнал включен в перечень Высшей Аттестационной Комиссии при Министерстве образования и науки Российской Федерации
  (<a href="http://vak.ed.gov.ru">ВАК</a>)
</p>

<p class="jounal-index">
  Статьям присваивается doi
</p>

<p>
  <a href="https://www.scimagojr.com/journalsearch.php?q=21100902867&amp;tip=sid&amp;exact=no" title="SCImago Journal &amp; Country Rank"><img border="0" src="https://www.scimagojr.com/journal_img.php?id=21100902867" alt="SCImago Journal &amp; Country Rank"  /></a>
</p>

<h4>Учредитель и издатель</h4>
<p>
  Санкт-Петербургский государственный университет
</p>

<h4>Адрес</h4>
<p>
  199034, Санкт-Петербург 
  <br/>
  Университетская наб. 7/9
</p>

<h4>Адрес редакции</h4>
<p>
  198504, Россия, Санкт-Петербург,
  <br/>
  Старый Петергоф,
  <br />
  Университетский пр., дом 28.
  <br />
  тел: (812) 428-4210,
  <br />
  факс: (812) 428-6944
</p>

<h4>E-mail</h4>
<p>
  JournalDECP@gmail.com
</p>