<h3>Адреса</h3>
<h4>Адрес редакции</h4>
<p>
198504<br /> 
Россия, Петергоф,<br /> 
Университетский проспект 28,<br /> 
математико-механический факультет,<br /> 
кафедра информатики<br />
</p>

<p>
Ампилова Наталья Борисовна<br />
Санкт-Петербургский Государственный Университет,<br />
тел.: +7 921 415 7762<br />
e-mail: <a href="mailto:n.ampilova@spbu.ru">n.ampilova@spbu.ru</a>
</p>
<h4>Техническая поддержка</h4>
<p>
Петренко Евгений Игоревич<br />
Санкт-Петербургский Государственный Университет,<br />
    e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>
<p>
    Мокаев Руслан Назирович<br />
    Санкт-Петербургский Государственный Университет,<br />
    e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>
<p>
    Кудряшова Елена Владимировна<br />
    Санкт-Петербургский Государственный Университет,<br />
    e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>

