<h2>Conferences</h2>

International Congress "Nonlinear Dynamical Analysis - 2007" dedicated to the 150th anniversary of Academician A.M.Lyapunov. 2007 June 4-8. Russian Academy of Sciences, Saint-Petersburg State University, Russia 
Eighth Crimean Workshop on the Method of Lyapunov Functions and its Applications 
Alushta, Crimea, Ukraine 
September 10-17, 2006 

"COMPUTER MODELLING OF DYNAMICAL SAYSTEMS" 
State Polytechnic University, Saint-Petersburg, Russia 
June 3-5 2004. 

MATHTOOLS'2003 
The Fourth International Conference 
"Tools for Mathematical Modelling" 
Saint-Petersburg State Technical University, 
Saint-Petersburg, Russia 
23-28, June, 2003 


International Scientific Conference 
DIFFERENTIAL EQUATIONS AND APPLICATIONS 
Samara, Russia 
26-31, May, 2002 


MATHTOOLS'2001 
The Third International Conference 
"Tools for Mathematical Modelling" 
Saint-Petersburg State Technical University, 
Saint-Petersburg, Russia 
