
<h3>Главный редактор</h3>
<h4><a href="http://apcyb.spbu.ru/nk">Кузнецов Николай Владимирович</a></h4>
<p>
дфмн, профессор<br />
Санкт-Петербургский Государственный Университет <br />
e-mail: <a href="mailto:n.v.kuznetsov@spbu.ru">n.v.kuznetsov@spbu.ru</a>
</p>

<h3>Заместитель Главного Редактора</h3>
<h4>Ампилова Наталья Борисовна</h4>
<p>
доцент, кфмн<br />
Санкт-Петербургский Государственный Университет<br />
тел.: +7 921 415 7762<br />
e-mail: <a href="mailto:n.ampilova@spbu.ru">n.ampilova@spbu.ru</a>
</p>

<h3>Техническая поддержка</h3>
<h4>Петренко Евгений Игоревич</h4>
<p>
кфмн<br />
Санкт-Петербургский Государственный Университет<br />
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a>
</p>
<h4>Мокаев Руслан Назирович</h4>
<p>
    кфмн<br />
    Санкт-Петербургский Государственный Университет<br />
    e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>

<h4>Кудряшова Елена Владимировна</h4>
<p>
    кфмн<br />
    Санкт-Петербургский Государственный Университет<br />
    e-mail: <a href="mailto:JournalDECP@gmail.com">JournalDECP@gmail.com</a>
</p>


$editorial_editorial_board()$