<h2>$editodial_page_caption()$</h2>

$about_content()$


<h3>Главный редактор</h3>
<ul><li>Осипенко Георгий Сергеевич</li></ul>

<h3>Заместители главного редактора</h3>
<ul>
  <li>Флегонтов Александр Владимирович,</li>
  <li>Пилюгин Сергей Юрьевич</li>
</ul>

<h3>Редактор</h3>
<ul><li>Ампилова Наталья Борисовна</li></ul>

<h3>Секретарь</h3>
<ul><li>Петренко Евгений Игоревич</li></ul>



$editorial_publishing_board()$

$editorial_editorial_board()$