<h2>$editodial_page_caption()$</h2>

$about_content()$

<h3>Главный редактор</h3>
<ul><li><strong>Леонов Геннадий Алексеевич</strong><br />член-корреспондент РАН, профессор, дфмн</li></ul>

<h3>Редактор</h3>
<ul><li><strong>Ампилова Наталья Борисовна</strong><br />доцент, кфмн</li></ul>

<h3>Техническая поддержка</h3>
<ul><li><strong>Петренко <!-- @jonnyzzz --> Евгений Игоревич</strong><br />кфмн</li></ul>


$editorial_editorial_board()$
