<!--<h3>Редакционная коллегия</h3>-->
<div class="board">

<div class="editor">
    <span class="name">Абрамович С.</span>
    <span class="title">Профессор</span>
    <span class="work">Университет Нью-Йорка, США</span>
    <span class="email">abramovs@potsdam.edu</span>
</div>
    
<div class="editor">
    <span class="name">Бодунов Н.А.</span>
    <span class="title">Профессор</span>
    <span class="work">Санкт-Петербургский Электротехнический Университет, Россия</span>
    <span class="email">nick.bodunov@gmail.com</span>
</div>

<div class="editor">
    <span class="name">Буркин И.М.</span>
    <span class="title">Профессор</span>
    <span class="work">Тульский государственный университет, Россия</span>
    <span class="email">i-burkin@yandex.ru</span>
</div>

<div class="editor">
    <span class="name">Зелинка И.</span>
    <span class="title">Профессор</span>
    <span class="work">Технический Университет Остравы (Чешская Республика)</span>
    <span class="email">ivan.zelinka@vsb.cz</span>
</div>

<div class="editor">
    <span class="name">Кудряшова Е.В.</span>
    <span class="title">Ведущий научный сотрудник</span>
    <span class="work">Санкт-Петербургский государственный университет, Россия</span>
    <span class="email">e.kudryashova@spbu.ru</span>
</div>

<div class="editor">
    <span class="name">Мокаев Р.Н.</span>
    <span class="title">Старший научный сотрудник</span>
    <span class="work">Санкт-Петербургский государственный университет, Россия</span>
    <span class="email">r.mokaev@spbu.ru</span>
</div>
    
    
<div class="editor">
    <span class="name">Нейтаанмяки П.</span>
    <span class="title">Профессор</span>
    <span class="work">Университет Ювяскюля, Финляндия</span>
    <span class="email">pekka.neittaanmaki@jyu.fi</span>
</div>

<div class="editor">
    <span class="name">Станкевич Н.В.</span>
    <span class="title">Старший научный сотрудник</span>
    <span class="work">НИУ "Высшая школа экономики" в Нижнем Новгороде, Россия</span>
    <span class="email">stankevichnv@mail.ru</span>
</div>

<div class="editor">
    <span class="name">Соловьев И.П.</span>
    <span class="title">доцент, кфмн</span>
    <span class="work">Санкт-Петербургский Государственный Университет</span>
    <span class="email">i.soloviev@spbu.ru</span>
</div>

<div class="editor">
    <span class="name">Осипенко Г.С.</span>
    <span class="title">Профессор</span>
    <span class="work">Филиал Московского государственного университета имени М.В. Ломоносова в городе Севастополе, Россия</span>
    <span class="email">george.osipenko@mail.ru</span>
</div>

<div class="editor">
    <span class="name">Пилюгин С.Ю.</span>
    <span class="title">Профессор</span>
    <span class="work">Санкт-Петербургский Государственный Университет, Россия</span>
    <span class="email">sergeipil47@mail.ru</span>
</div>

<div class="editor">
    <span class="name">Разван В.</span>
    <span class="title">Профессор</span>
    <span class="work">Крайовский университет, Румыния</span>
    <span class="email">vrasvan@automation.ucv.ro</span>
</div>

<div class="editor">
    <span class="name">Райтманн Ф.</span>
    <span class="title">Профессор</span>
    <span class="work">Санкт-Петербургский государственный университет, Россия</span>
    <span class="email">vreitmann@aol.com</span>
</div>

<div class="editor">
    <span class="name">Флегонтов А.В.</span>
    <span class="title">Профессор</span>
    <span class="work">Российский государственный педагогический университет им. А.И.Герцена, Россия</span>
    <span class="email">flegontoff@yandex.ru</span>
</div>

<div class="editor">
    <span class="name">Чен Г.</span>
    <span class="title">Профессор</span>
    <span class="work">Университет Гонконга, Китай</span>
    <span class="email">eegchen@cityu.edu.hk</span>
</div>

<div class="editor">
    <span class="name">Чечурин Л.</span>
    <span class="title">Профессор</span>
    <span class="work">Лаппеeнрантский технологический университет, Финляндия</span>
    <span class="email">Leonid.Chechurin@lut.fi</span>
</div>

<div class="editor">
    <span class="name">Шумафов М.М.</span>
    <span class="title">Профессор</span>
    <span class="work">Адыгейский государственный университет, Россия</span>
    <span class="email">magomet_sh@mail.ru</span>
</div>
    
</div>
