
<h3>Главный редактор</h3>
<h4><a href="$TemplateOsipenkoLink$">Осипенко Георгий Сергеевич</a>, проф.,</h4>
<p>
Санкт-Петербург<br>
e-mail: <a href="mailto:george.osipenko@mail.ru">george.osipenko@mail.ru</a>
</p>

<h3>Заместители главного редактора</h3>
<h4>Флегонтов Александр Владимирович, проф.,</h4>
<p>
Санкт-Петербургский Государственный Педагогический Университет,<br>
тел.: +7 812 492-2856(д), +7 812 571-44-61(р),<br>
e-mail: <a href="mailto:aflegontoff@herzen.spb.ru">aflegontoff@herzen.spb.ru</a>
</p>
<h4>Пилюгин Сергей Юрьевич, проф.,</h4>
<p>
Санкт-Петербургский Государственный Университет,<br>
e-mail: <a href="mailto:sp@sp1196.spb.edu">sp@sp1196.spb.edu</a>
</p>

<h3>Редактор</h3>
<h4>Ампилова Наталья Борисовна</h4>
<p>
Санкт-Петербургский Государственный Университет,<br>
тел.: +7 921 415 7762<br>
e-mail: <a href="mailto:nataly@is1483.spb.edu">nataly@is1483.spb.edu</a>
</p>

<h3>Секретарь</h3>
<h4>Петренко Евгений Игоревич</h4>
<p>
Санкт-Петербургский Государственный Университет,<br>
тел.: +7 921 957 5331<br>
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a>
</p>

$editorial_publishing_board()$

$editorial_editorial_board()$