<h3>Редакционная коллегия</h3>
<div class="board">

<div class="editor">
<span class="name">Абрамович С.</span>
<span class="title">профессор</span>
<span class="work">Университет Нью-Йорка (США)</span>
<span class="email">abramovs@potsdam.edu</span>
</div>

<div class="editor">
<span class="name">Аврицевич Я.</span>
<span class="title">профессор</span>
<span class="work">Технологический университет, Лодзь (Польша)</span>
<span class="email">jan.awrejcewicz@p.lodz.pl</span>
</div>
<div class="editor">
<span class="name">Бодунов Н. А.</span>
<span class="title">профессор, дфмн</span>
<span class="work">Санкт-Петербургский Электротехнический Университет (Россия)</span>
<span class="email">nick.bodunov@gmail.com</span>
</div>

<div class="editor">
<span class="name">Гуанрон Чен</span>
<span class="title">профессор</span>
<span class="work">Университет Гонконга (Китай)</span>
<span class="email">eegchen@cityu.edu.hk</span>
</div>

<div class="editor">
<span class="name">Фрадков А. Л.</span>
<span class="title">профессор, дфмн</span>
<span class="work">Институт проблем машиноведения РАН (Россия)</span>
<span class="email">fradkov@mail.ru</span>
</div>

<div class="editor">
<span class="name">Нейтаанмяки П.</span>
<span class="title">профессор</span>
<span class="work">Университет Ювяскюля (Финляндия)</span>
<span class="email">pekka.neittaanmaki@jyu.fi</span>
</div>

<div class="editor">
<span class="name">Матвеев А. С.</span>
<span class="title">профессор, дфмн</span>
<span class="work">Санкт-Петербургский Государственный университет (Россия)</span>
<span class="email">almat1712@yahoo.com</span>
</div>

<div class="editor">
<span class="name">Осипенко Г. С.</span>
<span class="title">профессор, дфмн</span>
<span class="work">Московский государственный университет им. Ломоносова, филиал в Севастополе</span>
<span class="email">george.osipenko@mail.ru</span>
</div>

<div class="editor">
<span class="name">Пилюгин С. Ю.</span>
<span class="title">профессор, дфмн</span>
<span class="work">Санкт-Петербургский Государственный Университет (Россия)</span>
<span class="email">sergeipil47@mail.ru</span>
</div>

<div class="editor">
<span class="name">Райтманн Ф.</span>
<span class="title">профессор, дфмн</span>
<span class="work">DAAD (Германия)</span>
<span class="email">vreitmann@aol.com</span>
</div>

<div class="editor">
<span class="name">Флегонтов А. В.</span>
<span class="title">профессор, дфмн</span>
<span class="work">Российский государственный педагогический университет им. А.И.Герцена</span>
<span class="email">flegontoff@yandex.ru</span>
</div>

<div class="editor">
<span class="name">Закржевски М. В.</span>
<span class="title">дфмн</span>
<span class="work">Рижский Технический Университет (Латвия)</span>
<span class="email">mzakr@latnet.lv</span>
</div>

<div class="editor">
<span class="name">Зелинка И.</span>
<span class="title">профессор</span>
<span class="work">Технический Университет Остравы (Чешская Республика)</span>
<span class="email">ivan.zelinka@vsb.cz</span>
</div>

</div>
