<h3>Редакционная коллегия</h3>
<div class="board">

<div class="editor">
<span class="name">Абрамович С.</span>
<span class="work">Университет Нью-Йорка (США)</span>
<span class="email">abramovs@potsdam.edu</span>
</div>

<div class="editor">
<span class="name">Андреев А.Ф., профессор, дфмн</span>
<span class="work">Санкт-Петербургский Государственный университет</span>
<span class="email">irandr124@gmail.com</span>
</div>

<div class="editor">
<span class="name">Аврицевич Я. </span>
<span class="work">Технологический университет, Лодзь (Польша)</span>
<span class="email">jan.awrejcewicz@p.lodz.pl</span>
</div>
<div class="editor">
<span class="name">Бодунов Н.А., профессор, дфмн</span>
<span class="work">Санкт-Петербургский Электротехнический Университет (Россия)</span>
<span class="email">nick.bodunov@gmail.com</span>
</div>

<div class="editor">
<span class="name">Гуанрон Чен</span>
<span class="work">Университет Гонконга (Китай)</span>
<span class="email">eegchen@cityu.edu.hk</span>
</div>

<div class="editor">
<span class="name">Фрадков А. Л., профессор, дфмн</span>
<span class="work">Институт проблем машиностроения РАН (Россия)</span>
<span class="email">fradkov@mail.ru</span>
</div>

<div class="editor">
<span class="name">Кузнецов Н.В., кфмн</span>
<span class="work">Университет Ювяскюля (Финляндия)</span>
<span class="work">Санкт-Петербургский Государственный университет (Россия)</span>
<span class="email">kuznetsov@math.spbu.ru</span>
</div>

<div class="editor">
<span class="name">Нейтанмяки П. </span>
<span class="work">Университет Ювяскюля (Финляндия)</span>
<span class="email">pekka.neittaanmaki@jyu.fi</span>
</div>

<div class="editor">
<span class="name">Матвеев А.С., профессор, дфмн</span>
<span class="work">Санкт-Петербургский Государственный университет (Россия)</span>
<span class="email">almat1712@yahoo.com</span>
</div>

<div class="editor">
<span class="name">Осипенко Г. С., дфмн.</span>
<span class="work">Московский государственный университет им. Ломоносова, филиал в Севастополе</span>
<span class="email">george.osipenko@mail.ru</span>
</div>

<div class="editor">
<span class="name">Пилюгин С.Ю., профессор, дфмн</span>
<span class="work">Санкт-Петербургский Государственный Университет (Россия)</span>
<span class="email">sergeipil47@mail.ru</span>
</div>

<div class="editor">
<span class="name">Рейтман Ф., профессор</span>
<span class="work">DAAD (Германия)</span>
<span class="email">vreitmann@aol.com</span>
</div>

<div class="editor">
<span class="name">Зайцев В.Ф., профессор, дфмн</span>
<span class="work">Российский государственный педагогический университет им. А.И.Герцена</span>
<span class="email">valentin_zaitsev@mail.ru</span>
</div>

<div class="editor">
<span class="name">Закржевски М.В., дфмн</span>
<span class="work">Рижский Технический Университет (Латвия)</span>
<span class="email">mzakr@latnet.lv</span>
</div>

<div class="editor">
<span class="name">Зелинка Иван</span>
<span class="work">Технический Университет Остравы (Чешская Республика)</span>
<span class="email">ivan.zelinka@vsb.cz</span>
</div>

</div>
