<h2>Правила оформления списка литературы в латинице</h2>
<p>
Для списка литературы в латинице (References) недопустимо применять российский ГОСТ Р 7.0.5-2008 
на библиографическую ссылку, который рекомендуется для списков литературы в русскоязычных источниках. 
Не используйте двойной слэш (//)!
</p>
<p>
    Рекомендуется использовать следующие схемы библиографических ссылок:
</p>

<ol>
   <li class="wide_number">Статья из журнала</li>
   <ul>
     <li>авторы (транслитерация)</li>
     <li>перевод заглавия статьи на английский язык в квадратных скобках</li>
     <li>название русскоязычного источника (транслитерация и курсивом)</li>
     <li>выходные данные с обозначениями на английском языке, либо только цифровые (последнее в зависимости от применяемого стандарта описания)</li>
     <li>указание на язык статьи (In Russ.) после описания статьи</li>
   </ul>

   <div class="paper_reference example">
      Byzov A.L., Utina I.A. The centrifugal effects on amacrine cells in the retina of frog. <em>Neirofiziologiya</em> ,1971; (3):293-300. (In Russ.)
   </div>

   <li class="wide_number">Книги, монографии</li>

   <ul>
      <li>автор(ы) ; </li>
      <li>название (транслитерация и курсивом); </li>
      <li>[перевод названия в квадратных скобках]; </li>
      <li> выходные данные:</li>
      <ul>
         <li>место издания на английском языке -Moscow, St.Petersburg;</li>
         <li>издательство на английском языке, если это организация (St.Petersburg St.
             Univ. Publ.),</li>
         <li>транслитерация, если издательство имеет собственное название, 
             с указанием на английском, что это издательство (Nauka Publ.);
         </li>
      </ul>
      <li>количество страниц в издании (400 p.). </li>
   </ul>

   <div class="paper_reference example">
      Pliss V.A. <em>Integralnie mnogestva periodicheskich sistem differencial'nih uravnenii </em>[Integral sets of periodic systems of differential equations]. Moscow, Nauka Publ., 1977. 304 p.
   </div>
   

   <li class="wide_number">Статья из электронного журнала</li>
    
   <div class="paper_reference example">
     Anosov D.V., Zhuzhoma E.V. [Closing lemmas]. <em>Differencial'nie uravnenia i processy </em>upravlenia<em>, </em>2012, no. 1 (In Russ.) Available at:    <a href="http://www.math.spbu.ru/diffjournal/pdf/anosov_zuzoma.pdf">http://www.math.spbu.ru/diffjournal/pdf/anosov_zuzoma.pdf</a>
   </div>

   <li class="wide_number">Статья из продолжающегося издания (сборника трудов)</li>
   
   <div class="paper_reference example">
       Astakhov M.V., Tagantsev T.V [Experimental study of the strength of joints "steelcomposite"].    <em>Trudy MGTU "Matematicheskoe modelirovanie slozhnykh tekhnicheskikh system"</em>[Proc. of the Bauman MSTU "Mathematical Modeling of Complex Technical Systems"], 2006, no. 593, pp.125-130. (In Russian)
   </div>

   <li class="wide_number">Описание материалов конференций</li>
   <div class="paper_reference example">  
      Ampilova N.B., Soloviev I.P., Shupletsov Y.V. [On the application of image analysis and classification methods in biomedical researches].    <em>Trudy Mezhdunarodnoi Nauchno-Tekhnicheskoi Konferenzii "Komp'iyternoe Modelirovanie 2013 "</em> [Proc. Int. Conf. "Computer Modeling 2013"], St.Petersburg, 2013, pp. 106-111. (In Russian)
   </div>

   <li class="wide_number">Описание переводной книги</li>
   <div> Если можно выявить оригинал, по которому был сделан перевод, то полезно описать его вместо переводного. Можно описать русскоязычное переводное издание,
    указав настоящие англоязычные фамилии авторов. </div>
  
   <div>
    Если не удается выявить сведения об оригинальной версии книги или оригинальных фамилиях авторов, в основном описании остается переводное издание.
   </div>
   
   <div class="paper_reference example">
       Brooking A., Jones P., Cox F. <em>Expertnye sistemy. Prinsipy raboty i primery.</em>[Expert systems. Principles and case studies], Moscow, Radio i sviaz' Publ., 1987, 224 p.
   </div>

   <li class="wide_number">Описание Интернет-ресурса</li>
   <div class="paper_reference example">
       Kondrat'ev V.B. <em>Global'naya farmatsevticheskaya promyshlennost'</em>[The global pharmauceutical industry]. Available at: e-address. (accessed 23.06.2013)
   </div>

   <li class="wide_number">Описание диссертации или автореферата диссертации</li>
   <div class="paper_reference example">
      Semenov V.I. <em>Matematicheskoe modelirovanie plasmy v sisteme compaktny tor. </em>Dokt. Diss. [Mathematical modeling of the plasma in the compact torus. Doct. Diss.], Moscow, 2003, 272 p.
   </div>
</ol>


