<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
  <head>
    <title>Журнал дифференциальные уравнения и процессы управления - $caption$</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
    <link rel="stylesheet" href="$ResourceLink$/style.css" type="text/css"></link>
    <script type="text/javascript" src="$ResourceLink$/jquery.js"></script>
    <script type="text/javascript" src="$ResourceLink$/journal.js"></script>
  </head>
  <body>
    <div class="Head">
      <div class="UniversityFounderLogo">
        <a href="https://spbu.ru/" title="Санкт-Петербургский государственный университет">
          <img src="$ResourceLink$/SPbSU_Logo.svg" alt="СПбГУ"></img>
        </a>
      </div>
      <div class="Logo">
        <a href="$TemplateAboutLink$" title="О журнале">
          $logo$
        </a>
      </div>
      <div class="HeadForeignLink">
        <a href="$ForeignLink$">English version</a>
      </div>
                                     
      <div class="issn"><a href="$TemplateAboutLink$#fromLogo">ISSN 1817-2172, рег. Эл. № ФС77-39410, ВАК</a></div>

      <h1>Дифференциальные Уравнения<br />и<br />Процессы Управления</h1>
    </div>
    <div class="MainMenu">
      $menu$
    </div>
    <div class="Content">
      $content$
    </div>
    <div class="Footer">
      <div class="FooterLinks">
        <a href="$TemplatePrivacyLink$">
          Политика в отношении обработки персональных данных
        </a>
      </div>
      <div class="FooterCopyright">
        © Санкт-Петербургский государственный университет, $CurrentYear$
      </div>
    </div>
    <div id="cookieConsentBanner"
         class="CookieConsent"
         style="display:none;">

      <div class="CookieConsentText">
        Используя сайт, Вы соглашаетесь с тем, что СПбГУ применяет файлы cookie
        и сервисы веб-аналитики. Продолжая работу с сайтом, Вы даете свое
        <a href="$TemplatePrivacyLink$">
          согласие на обработку персональных данных
        </a>.
        Вы можете управлять настройками cookie в Вашем браузере.
      </div>

      <button id="cookieConsentAccept" type="button">
        Соглашаюсь
      </button>
    </div>
  </body>
</html>