<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
  <head>
    <title>Журнал дифференциальные уравнения и процессы управления - $caption$</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
    <!-- Journal generator by Eugene @jonnyzzz Petrenko (eugene[dot]petrenko(at)gmail_com), thanks to Nikita Raba -->
    <link rel="stylesheet" href="$ResourceLink$/style.css" type="text/css"></link>
    <script type="text/javascript" src="$ResourceLink$/google.analytics.js"></script>
    <script type="text/javascript" src="$ResourceLink$/jquery.js"></script>
    <script type="text/javascript" src="$ResourceLink$/journal.js"></script>
  </head>
  <body>
    <div class="Head"> 
      <div class="Logo">
        $logo$
      </div>
      <div class="HeadForeignLink">
        <a href="$ForeignLink$">English version</a>
      </div>
                                     
      <div class="issn"><a href="$TemplateAboutLink$#fromLogo">ISSN 1817-2172, рег. Эл. № ФС77-39410, ВАК</a></div>

      <h1>Дифференциальные Уравнения<br />и<br />Процессы Управления</h1>
    </div>
    <div class="MainMenu">
      $menu$
    </div>
    <div class="Content">
      $content$
    </div> 
    <div class="Footer">
    </div>
  </body>
</html>