<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
  <head>
    <title>Журнал дифференциальные уравнения и процессы управления - $caption$</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
    <!-- Journal generator by Eugene Petrenko (eugene[dot]petrenko(at)gmail_com), thanks to Nikita Raba" -->
    <link rel="stylesheet" href="$ResourceLink$/style.css" type="text/css"></link>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17795545-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

  </head>
  <body>
    <div class="Head"> 
      <div class="Logo">
        $logo$
      </div>
      <div class="HeadForeignLink">
        <a href="$ForeignLink$">English version</a>
      </div>
                                     
      <div class="issn">ISSN 1817-2172, рег. Эл. № ФС77-39410</div>

      <h1>Дифференциальные Уравнения<br />и<br />Процессы Управления</h1>
    </div>
    <div class="MainMenu">
      $menu$
    </div>
    <div class="Content">
      $content$
    </div> 
    <div class="Footer">
      Старая версия сайта доступна <a href="http://www.neva.ru/journal/rus/r_main.htm">здесь</a>
    </div>

  </body>
</html>