<img src="$ResourceLink$/osipenko.jpg" style="float:left; margin:3em" alt="Photo">
<h2>Осипенко<br>Георгий Сергеевич</h2>	
<p>
e-mail: george[dot]osipenko]at[mail.ru 
</p>
<h3>Academic title:</h3>
<ol>
<li>Professor of Mathematics, St. Petersburg State Technical University, 1990 </li>
<li>Doctor of Sciences, St. Petersburg State University, 1989 </li>
<li>Phd, Leningrad State University, 1975 </li>
</ol>
<h3>Institutional affiliations:</h3>
<ol>
<li>1992 to present – Director of Laboratory of Nonlinear Analysis and Mathematical Simulation, St. Petersburg State Technical University; </li>
<li>1990 to present – Professor, Dept. of Higher Mathematics, St. Petersburg State Technical University; </li>
<li>2000 – Visiting Professor, Suleyman Demirel University, Isparta, Turkey; </li>
<li>1995 – Visiting Professor, School of Sciences, Belmont University, Nashville, USA; </li>
<li>1993 – Visiting Professor, Institute of Science and Technology, South Korea; </li>
<li>1975-1990 – Associated Professor, Dept. of Higher Mathematics, St. Petersburg State Technical University, St. Petersburg, Russia; </li>
</ol>
<h3>Teaching courses:</h3>
<ol>
<li>Computer Modeling of Dynamical System </li>
<li>Applied Mathematics </li>
<li>Differential Equations </li>
<li>Applied Symbolic Dynamics </li>
<li>Invariant Manifolds</li>
</ol>
<h3>Languages:</h3>
<ol>
<li>English </li>
<li>French </li>
<li>Russian</li>
</ol>
<h3>Scientific fields:</h3>
<ol>
<li>Computer Modeling of Dynamical Systems </li>
<li>Differential Equations </li>
<li>Dynamical Systems </li>
<li>Optimization </li>
<li>Control Theory </li>
<li>Applied Symbolic Dynamics and Chaos </li>
<li>Theory of invariant manifolds </li>
</ol>
<h3>International activity:</h3>
<p>
<ol>
<li>Conference "The Conley Index and Related Topics", Sherbrooke, Canada. 2001 </li>
<li>Conference "Mathematical Modeling", Ankara, Turkey, 2001 </li>
<li>Workshop "Theory of Singularity", Cambridge, England, 2000 </li>
<li>Wold Congress of Nonlinear Analysts", Cecilia, Italy, 2000 </li>
<li>International Conference "Differential Equations", Berlin, Germany, 1999 </li>
<li>Third Conference "Nonlinear Oscillations", Copenhagen, Denmark, 1999 </li>
<li>Wold Mathematical Congress, Berlin, Germany, 1998 </li>
<li>Symposium "Mathematical Theory of Networks", Padova, Italy, 1998 </li>
<li>and about 20 other International Conferences. </li>
</ol>
Organizer of 5 International Conferences "Differential Equations and Application" and "Tools for Mathematical Modeling" 
</p>
<h3>Publications:</h3>
<p>
Publications of Prof. G.Osipenko: 75 papers.Some publications: 
<ul>
<li>D.Mizin, G.Osipenko, S.Kobyakov, The estimates for the topological entropy of the dynamical system, Tools for mathematical modeling, Mathematical research, v.8 (2001), 85-105. </li>
<li>G.Osipenko, S.Ayter, S.Kobyakov, The structure matrix of dynamical system, Tools for mathematical modeling, Mathematical research, v.8 (2001), 106-114. </li>
<li>G.Osipenko, S.Pehlivan Verification of structural stability, Tools for mathematical modeling, Mathematical research, v.8 (2001), 115-126. </li>
<li>D. Mizin, G. Osipenko, S. Pechlivan, Relation between the topological entropy of dynamical system and the entropy of the symbolic image, Mathematics Recearch, v.6, Theory and Practice of Differential Equations, St.Petersburg, 2000, 142-148. </li>
<li>G.Osipenko, Calculation of Lyapunov exponents by applied symbolic dynamics, International Journal of Nonlinear Sciences and Numerical Simulation, v. 2, no. 1, 53-72, (2001). </li>
<li>G.Osipenko, Spectrum of a dynamical system and applied symbolic dynamics, Journal of Mathematical Analysis and Applications, 252, 587-616 (2000). </li>
<li>G.Osipenko and S.Campbell, Applied Symbolic Dynamics: attractors and filtrations, Discrete and Continuous Dynamical Systems, U.S.A., v.5, no.1-2, 1999, 43-60. </li>
<li>G.Osipenko, Morse Spectrum of Dynamical Systems and Symbolic Dynamics, in Proceedings of 15th IMACS World Congress, v.1, 1997, 25-30. </li>
<li>G.Osipenko and I.Il'in, Methods of Applied Symbolic Dynamics, Dynamical Systems and Applications, v. 2, Atlanta, Dynamic Pablishers Inc., USA, 1996, 451-459. </li>
<li>G.Osipenko, Computer Modelling of Dynamical Systems, Proc. Symp. on Modelling, Analysis and Simulation, Lille, France, 1996, 999-1004. </li>
<li>G.Osipenko, Linearization Near a Locally Nonunique Invariant Manifold, Discrete and Continuous Dynamical Systems, U.S.A., v.3, no.2, 1997, 189-205. </li>
<li>G.Osipenko, Indestructibility of Invariant Locally Nonunique manifolds, Discrete and Continuous Dynamical Systems, U.S.A., v.2, no.2, 1996, 203-219. </li>
<li>G.Osipenko, E.Ershov and J.Kim Lectures on Invariant Manifolds of Perturbed Differential Equations and Linearization, St.Petersburg, 1996, 153p, (monograph). </li>
<li>G.Osipenko, E.Ershov, Perturbation of invariant manifolds of ordinary differential equations, Six Lectures on Dynamical Systems, edit. B.Aulbach and F.Colonius, World Scientific, Singapore, 1996, 213-265, (monograph). </li>
</ul>
</p>
<h3>Some Books:</h3>
<p>
  <ul>
    <li><a href="$ResourceLink$/books/book_gs_ampi.pdf">Lectures On Symbolic Analysis of Dynamical Systems</a></li>
  </ul>
</p>
<p>
<img src="$ResourceLink$/osipenko2.jpg" alt="Photo" /> <br />
Jim Yorke and Osipenko G.S.
</p>