    <a class="MenuElement" href="$TemplateAboutLink$">
      About
    </a>
    <a class="MenuElement" href="$TemplateEditorial_StaffLink$">
      Editorial staff
    </a>
    <a class="MenuElement" href="$NewsLink$">
      News
    </a>
    <a class="MenuElement" href="$TemplateFor_AuthorsLink$">
      For authors
    </a>
    <a class="MenuElement" href="$BooksLink$">
      Books
    </a>
    <a class="MenuElement" href="$CollectionLink$">
      Collection
    </a>
    <a class="MenuElement" href="$ForeignLink$">
      Русская версия 
    </a>