<html>
  <head>
    <title>Журнал дифференциальные уравнения и процессы управления - $caption$</title>
    <meta http-equiv=Content-Type content="text/html; charset=UTF-8">
    </meta>
    <link rel="stylesheet" href="$ResourceLink$/style.css" type="text/css"></link>
  </head>
  <body>
    <div class="Head"> 
      <div class="Logo">
        $logo$
      </div>
      <div class="HeadForeignLink">
        <a href="$ForeignLink$">English version</a>
      </div>
      <h1>Дифференциальные Уравнения<br>и<br>Процессы Управления</h1>
    </div>
    <div class="MainMenu">
      $menu$
    </div>
    <div class="Content">
      $content$
    </div> 
  </body>
</html>