<h2>About Journal</h2>

<h3>Status</h3>
<h4>Licensing Authority</h4>
<p>
State Publishing Committee of the Russian Federation,<br>
North-western Regional Department, Saint-Petersburg,<br>
Registration number: P 2375 on March 7, 1997
</p>
<h4>Promoter</h4>
<p>
Saint-Petersburg State Technical University<br>
Saint-Petersburg State University
</p>

<h3>Address</h3>
<h4>Editorial office address</h4>
<p>
198504<br> 
Russia, Peterhof,<br> 
Universitetskii pr., 28,<br> 
Mathematics & Mechanics faculty,<br> 
dept. of Computer Science<br>
Editor: Ampilova Natalya
</p>
<h4>Editor:</h4>
<p>
Natalya B. Ampilova<br>
Assoc.Prof., Dept. of Comp. Sci, St.Petersburg State University,<br>
St. Petersburg, Russia<br>
tel: +7 812 776 7611<br>
e-mail: <a href="mailto:nataly@is1483.spb.edu">nataly@is1483.spb.edu</a>
</p>
<h4>Executive Secretary:</h4>
<p>
Eugene I. Petrenko<br>
Dept. of Comp. Sci, St.Petersburg State University<br>
St. Petersburg, Russia<br>
tel: +7 921 957 5331<br>
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a>
</p>

<h3>Scope of the Journal</h3>
<p>
The scope of the journal encompasses the following fields of study:
<ul>
<li>ordinary differential equations </li>
<li>nonlinear oscillations </li>
<li>differential-difference equations </li>
<li>dynamical systems on manifolds </li>
<li>bifurcation </li>
<li>symbolic dynamics </li>
<li>integro-ordinary differential equations </li>
<li>group analysis of differential equations </li>
<li>differential equations with randomness </li>
<li>general control problems </li>
<li>adaptive and robust control </li>
<li>control problems in nonlinear and sophisticated systems </li>
<li>filtration and identification </li>
<li>synchronization of oscillatory and chaotic processes </li>
<li>optimal control </li>
<li>numerical methods </li>
<li>computer modeling in dynamical and control systems </li>
<li>computer software for investigation of differential </li>
<li>equations, dynamical systems, and control processes </li>
<li>applications to physics, electrotechnics, and electronics </li>
<li>dynamical systems in medicine, biology, ecology, and chemistry </li>
<li>dynamic economic models</li>
</ul>
</p>
<p>
The Journal accepts original contributions, review articles, conference proceedings, monographs, lectures and courses of lectures, theses and author's abstracts, computer software, and other items with a detailed exposition of results, proofs, and examples and related to the fields listed above. 
</p>
<p>
Related to the journal scope, the Editorial Board accepts educational courses and software, methodological papers, materials on teaching methods, and information about monographs, textbooks, theses, software, seminars, conferences etc. 
</p>
<p>
The Editorial Board also accepts items in other fields related to the journal scope.
</p>