<h2>Journal's Editorial Board</h2>

<h3>Editor-in-Chief:</h3>
<h4>George S. Osipenko</h4>
<p>
Prof., Dr.Sci., Dept. of Mathematics,<br>
State Polytechnical University, St. Petersburg, Russia<br>
e-mail: <a href="mailto:george.osipenko@mail.ru">george.osipenko@mail.ru</a>
</p>

<h3>Assistant Editors:</h3>
<h4>Alexandr V. Flegontov</h4>
<p>
Prof., Dr.Sci., Dept. of Informatics & Technology,<br>
Herzen State Pedagogical University, St. Petersburg, Russia<br>
tel: +7 812 492-2856, +7 812 571-44-61,<br>
e-mail: <a href="mailto:aflegontoff@herzen.spb.ru">aflegontoff@herzen.spb.ru</a>
</p>
<h4>Sergey Yu. Pilyugin</h4>
<p>
Prof., Dr.Sci., St.Petersburg State University,<br>
St. Petersburg, Russia<br>
e-mail: <a href="mailto:sp@sp1196.spb.edu">sp@sp1196.spb.edu</a>
</p>

<h3>Editor:</h3>
<h4>Natalya B. Ampilova</h4>
<p>
Assoc.Prof., Dept. of Comp. Sci, St.Petersburg State University,<br>
St. Petersburg, Russia<br>
tel: +7 812 776 7611 <br>
e-mail: <a href="mailto:nataly@is1483.spb.edu">nataly@is1483.spb.edu</a>
</p>

<h3>Executive Secretary:</h3>
<h4>Eugene I. Petrenko<h4>
<p>
Dept. of Comp. Sci, St.Petersburg State University<br>
St. Petersburg, Russia<br>
tel: +7 921 9575331<br>
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a>
</p>

<h3>Publishing Board:</h3>
<ul>
<li>A.G. Chentzov (Dr. Sci., Ekaterinburg),</li>
<li>A.L. Fradkov (Dr. Sci., St. Petersburg),</li>
<li>C.K. Korovin (Dr. Sci., Moscow),</li>
<li>N.N. Krasovskii (Dr. Sci., Ekaterinburg),</li>
<li>A.B. Kurshanskii (Dr. Sci., Moscow),</li>
<li>G.A. Leonov (Dr. Sci., St. Petersburg),</li>
<li>L.A. Mironovskii (Dr. Sci., St. Petersburg),</li>
<li>V.A. Palmov (Dr. Sci., St. Petersburg),</li>
<li>L.A. Petrosian (Dr. Sci., St. Petersburg),</li>
<li>V.A. Pliss (Dr. Sci., St. Petersburg),</li>
<li>N.C. Rosov (Dr. Sci., Moscow),</li>
<li>V.A. Yakubovitch (Dr. Sci., St. Petersburg)</li>
</ul>

<h3>Editorial Board:</h3>
<ul>
<li>A.F. Andreev (Dr. Sci., St. Petersburg),</li>
<li>N.E. Barabanov (Dr. Sci., St. Petersburg),</li>
<li>Yu.N. Bibikov (Dr. Sci., St. Petersburg),</li>
<li>Yu.V. Churin (Dr. Sci., St. Petersburg),</li>
<li>V.M. Ivanov (Dr. Sci., St. Petersburg),</li>
<li>E.K. Ershov (Assoc.Prof., St. Petersburg),</li>
<li>V.N. Kozlov (Dr. Sci., St. Petersburg),</li>
<li>G.G. Malinechkii (Dr. Sci., Moscow),</li>
<li>A.S. Matveev (Dr. Sci., St. Petersburg),</li>
<li>I.V. Miroshnik (Dr. Sci., St. Petersburg),</li>
<li>N.N. Petrov (Dr. Sci., St. Petersburg),</li>
<li>S.Yu. Piliugin (Dr. Sci., St. Petersburg),</li>
<li>G.Yu. Riznichenko (Dr. Sci., Moscow),</li>
<li>E.N. Rozenvasser (Dr. Sci., St. Petersburg),</li>
<li>A.I. Shepeliavui (Assoc.Prof., St. Petersburg),</li>
<li>V.B. Smirnova (Dr. Sci., St. Petersburg),</li>
<li>A.V. Timofeev (Dr. Sci., St. Petersburg),</li>
<li>S.M. Ustinov (Dr. Sci., St. Petersburg),</li>
<li>V.F. Zaitsev (Dr. Sci., St. Petersburg),</li>
<li>A.V. Zinkovskii (Dr. Sci., St. Petersburg)</li>
</ul>