<h2>Information for authors</h2>

<h3>Scope of the Journal</h3>
<p>
The scope of the journal encompasses the following fields of study: 
<ul>
<li>ordinary differential equations </li>
<li>nonlinear oscillations </li>
<li>differential-difference equations </li>
<li>dynamical systems on manifolds </li>
<li>bifurcation </li>
<li>symbolic dynamics </li>
<li>integro-ordinary differential equations </li>
<li>group analysis of differential equations </li>
<li>differential equations with randomness </li>
<li>general control problems </li>
<li>adaptive and robust control </li>
<li>control problems in nonlinear and sophisticated systems </li>
<li>filtration and identification </li>
<li>synchronization of oscillatory and chaotic processes </li>
<li>optimal control </li>
<li>numerical methods </li>
<li>computer modeling in dynamical and control systems </li>
<li>computer software for investigation of differential </li>
<li>equations, dynamical systems, and control processes </li>
<li>applications to physics, electrotechnics, and electronics </li>
<li>dynamical systems in medicine, biology, ecology, and chemistry </li>
<li>dynamic economic models </li>
</ul>
</p>
<p>
The Journal accepts original contributions, review articles, conference proceedings, monographs, lectures and courses of lectures, theses and author's abstracts, computer software, and other items with a detailed exposition of results, proofs, and examples and related to the fields listed above. 
</p>
<p>
Related to the journal scope, the Editorial Board accepts educational courses and software, methodological papers, materials on teaching methods, and information about monographs, textbooks, theses, software, seminars, conferences etc. 
</p>
<p>
The Editorial Board also accepts items in other fields related to the journal scope. 
</p>

<h3>How to prepare a paper</h3>
<h4>The following matters must be submitted to the Editorial Board:</h4>
<ol>
<li>Typescript copy of the manuscript </li>
<li>Abstracts in Russian and English </li>
<li>Author's application form including
<ul>
  <li>author's surname, first name, and patronymic </li>
  <li>postal address </li>
  <li>e-mail, phone, fax </li>
  <li>institution and position </li>
  <li>scientific degree and rank </li>
</ul></li>
<li>Covering letter containing
<ul>
  <li>a scientific direction to which the paper relates </li>
  <li>possible referees of the paper </li>
  <li>a hard copy of one review (optional)</li>
</ul></li>
<li>Files containing the manuscript and prepared in accordance with the instruction below. </li>
</ol>
<h4>Electronic publication is realized as follows:</h4>
<p>
Paper's abstract is displayed at the Journal home page in INTERNET with text of article in pdf-format and zip-archive of tex-files. 
</p>
<h4>Submission of the paper</h4>
<p>
The paper is submitted as TEX- and DVI-files; figures (if necessary) are prepared in the PCX or BMP-format. The author(s) submits a file containing a complete text of the paper with an abstract and a file of an abstract (in Russian and English) separate from the paper file. Files are to be prepared with the use of LATEX 2.09 or LATEX-2e. Files may be sent by ordinary mail on a diskette of the standard DOS format (1.44Mb-3.5'') or by E-mail. Two hard copies of the paper must necessarily be sent for reviewing purposes. 
</p>
<p>
The paper is to be prepared in accordance with the journal style. For this you need to invoke the instruction for authors below. Authors may appeal to the Editorial Board for aid. 
</p>
<h4>Instruction for authors</h4>
<uL>
<li>Load the file <a href="$ResourceLink$/auth-for.zip">author-for.zip</a> from the INTERNET site to your computer. Unpack it by the command: <b>pkunzip -d author-for.zip</b> and enter the directory AUTH-FOR. </li>
<li> Select the language of the paper (Russian/English).</li>
</ul>
<h4>If the language is Russian:</H3>
<ol>
<li>Enter the directory AUTH-FOR\RUSSIAN\EXAMPLE.</li>
<li>Compile the samples of a paper and an abstract using <b>LATEX 2.09</b> or <b>LATEX-2e</b>. The starting files for compilation are <b>russian.tex</b> <b>referat.tex</b></li>
<li>In the screen mode, familiarize yourself with the samples of a paper and an abstract written according to the journal requirements.</li>
<li>To prepare your paper enter the directory AUTH-FOR\RUSSIAN\BLANKS.</li>
<li>Type-set a paper and an abstract as <b>name-art.tex</b> and <b>name-ref.tex</b>, respectively, using any of MS DOS editors (me, ne, q, etc) and the headings contained in these files.</li>
<li>Compile the files <b>name-art.tex</b> and <b>name-ref.tex</b> similar to the example.</li>
<li> Files <b>name-art.tex</b>, <b>name-ref.tex</b>, and a file containing author's application form are packed in a single file with the extension<b> .arj (.zip)</b>by<b> ARJ (ZIP)</b> achievers program and are sent to the Editorial Board.</li>
</ol>
<h4>If the language is English:</h4>
<ol>
<li>Enter the directory AUTH-FOR\ENGLISH\EXAMPLE.</li>
<li>Compile the samples of a paper and an abstract using<b> LATEX 2.09</b> or <b>LATEX-2e</b>. The starting files for compilation are <b>english.tex</b><b>referat.tex</b></li>
<li>In the screen mode, familiarize yourself with the samples of a paper and an abstract written according to the journal requirements.</li>
<li>To prepare your paper enter the directory AUTH-FOR\ENGLISH\BLANKS.</li>
<li>Type-set a paper and an abstract as name-art.tex and name-ref.tex, respectively, using any of MS DOS editors (me, ne, q, etc) and the headings contained in these files.</li>
<li>Compile the files name-art.tex and name-ref.tex similar to the example.</li>
<li>Files name-art.tex, name-ref.tex, and a file containing author's application form are packed in a single file with the extension <b>.arj (.zip)</b> by<b> ARJ (ZIP)</b> archives program and are sent to the Editorial Board.</li>
</ol>
<h4>Information for authors</h4>
<ol>
<li>The working languages of the Journal are English and Russian.</li>
<li>A paper abstract in English and Russian may not exceed four  A4-pages (2+2).</li>
<li>The paper volume is not limited.</li>
<li>Matters published in the Electronic Journal may be used by the author in other publications.</li>
<li>The Editorial Board does not return matters sent by the author(s).</li>
</ol>
<h4>Papers are to be sent to</h4>
<p>
198504 <br> 
Russia, Peterhof, <br>
Universitetskii pr., 28,  <br>
Mathematics & Mechanics faculty, <br> 
dept. of Computer Science<br>
Ampilova Natalya, <br>
tel.: +7 812 776 76 11<br>
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a><br>
<a href="http://www.neva.ru/journal">http:/www.neva.ru/journal</a>
</p>

<h3>How to submit a paper</h3> 
<h4>The following matters must be submitted to the Editorial Board:</h4>
<ol>
<li>Typescript copy of the manuscript</li>
<li>Abstracts in Russian and English</li>
<li>Author's application form including
<ul>
   <li>author's surname, first name, and patronymic</li>
   <li>postal address</li>
   <li>e-mail, phone, fax</li>
   <li>institution and position</li>
   <li>scientific degree and rank</li>
</ul></li>
<li>Covering letter containing
<ul>
   <li>a scientific direction to which the paper relates</li>
   <li>possible referees of the paper</li>
   <li>a hard copy of a review (optional)</li>
</ul></li>
<li>Files  containing the manuscript and prepared in accordance with the instruction below.</li>
</ol>
<h4>Electronic publication is realized as follows:</h4>
<ul>
<li>paper's abstract is displayed at the Journal home page in INTERNET</li>
<li>the complete text of the paper is available for the reader under request</li>
<li>if requested, the complete text of the paper is sent to the reader as a <b>tex</b>-file  and (or) a <b>dvi</b>-file</li>
</ul>
<h4>The Editorial Board does not return matters sent by the author(s).</h4>
<h4>Papers are to be sent to</h4>
<p>
198504 <br> 
Russia, Peterhof, <br>
Universitetskii pr., 28,  <br>
Mathematics & Mechanics faculty, <br> 
dept. of Computer Science<br>
Ampilova Natalya, <br>
tel: +7 812 776 7611, +7 921 957 5331<br>
e-mail: <a href="mailto:nataly@is1483.spb.edu">nataly@is1483.spb.edu</a><br>
e-mail: <a href="mailto:jodiff@mail.ru">jodiff@mail.ru</a><br>
<a href="http://www.neva.ru/journal">http:/www.neva.ru/journal</a>
</p>

<h3>Where you can get LaTEX?</h3>

<h4>Russian version:</h4>
<p>
in Moskow, Russia: (095)286-06-22, 286-17-77
</p>
<p>
All information about MikTex you can find at <a href="http://www.miktex.org">http://www.miktex.org</a><br>
LaTeX is a module in the MikTex package.
</p>
<h4>English version:</h4>
<p>
- Anonymous ftp:<br>
<a href="ftp://ftp.dante.de/tex-archive/systems/msdos/emtex">ftp.dante.de/tex-archive/systems/msdos/emtex</a><br>
<a href="ftp://ftp.shsu.edu/tex-archive/systems/msdos/emtex">ftp.shsu.edu/tex-archive/systems/msdos/emtex</a><br>
<a href="ftp://ftp.tex.ac.uk/tex-archive/systems/msdos/emtex">ftp.tex.ac.uk/tex-archive/systems/msdos/emtex</a><br>
</p>
<p>
- Mail server:<br>
<a href="mailto:ftpmail@dante.de">ftpmail@dante.de</a><br>
<a href="mailto:ftpmail@ftp.SHSU.edu">ftpmail@ftp.SHSU.edu</a>
</p>
<p>
Note that BINARY mode must be used for downloading all the files.
</p>

