<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Journal Differential Equations and Control Processes - $caption$</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </meta>
    <link rel="stylesheet" href="$ResourceLink$/style.css" type="text/css"></link>
  </head>
  <body>
    <div class="Head">
      <div class="Logo">
        $logo$
      </div>
      <div class="HeadForeignLink">
        <a href="$ForeignLink$">Русская версия</a>
     </div> 
     <h1>Differential Equations<br />and<br />Control Processes</h1>
    </div>
    <div class="MainMenu">
      $menu$
    </div>
    <div class="Content">
      $content$
    </div> 
  </body>
</html>