<html>
  <head>
    <title>Journal Differential Equations and Control Processes - $caption$</title>
    <meta http-equiv=Content-Type content="text/html; charset=UTF-8">
    </meta>
    <link rel="stylesheet" href="$ResourceLink$/style.css" type="text/css">
    </link>
  </head>
  <body>
    <div class="Head">
      <div class="Logo">
        $logo$
      </div>
      <h1>Differential Equations<br>and<br>Control Processes</h1>
      <div class="Menu">
        $menu$
      </div>
    </div>
    <div class="Content">
      $content$
    </div> 
  </body>
</html>